### ISSUE TITLE
Improving practices around performance with Apostrophe

### ISSUE THREAD

**Issue by agilbert** [punkave/best-practices#11]
Great talk today, Tom!

Wanted to capture notes and next steps we discussed regarding our practices around the performance of Apostrophe.

**apostrophe-debug**
Sick module, I'm really glad this exists. The main issue now is that its default output is too verbose if you have it enabled, so I would advocate for the following:
- add a summary output style, decide on which key metrics this should report, really just a single line of important stuff that would trigger further investigation by the developer
- if you enable the module in your project, it shows this summary output
- developers should be able to run `node app --debug` or `node app --verbose` if they want to see the full output
- once the above is working, let's go ahead and put this in our default boilerplate project and document how everything works

**HOWTOs**
The `filters` stuff seems great and powerful, but as I said in the meeting, it's still something that I only understand as: "Tom told me if I do this thing it will make my code not as broken." It seems like it makes sense to create a specific HOWTO for "Improving performance of your Apostrophe project" or something along those lines that dives deep into how `filters` and `projections` and `areas: false` and all of that works. This would be super helpful for both P'unks and developers outside P'unk.

Does this make sense to everyone?

**Comment by agilbert** [comment]
See https://github.com/punkave/apostrophe-debug/issues/1

**Comment by agilbert** [comment]
See https://github.com/punkave/apostrophe-documentation/issues/30

**Comment by austinstarin** [comment]
Closing this out. Not sure how relevant this is anymore and if it is maybe should live somewhere else.

**Comment by boutell** [comment]
This is well documented now as far as recommendations for joins go, I think closing it is fine.

**Comment by austinstarin** [comment]
Awesome. Thanks @boutell
