### ISSUE TITLE
What are the high-level criteria that guide and govern our best practices at P'unk Avenue

### ISSUE THREAD

**Issue by colpanik** [punkave/best-practices#13]
Before we can "canonize" practices into the READMEs of this repo, we'd like to establish a set of criteria that we can use to measure potential BPs...

These should be high-level principals that aren't necessarily specific to any patterns or technologies. This list would live on the homepage of the README and serve as our commandments.
#### Some Good Examples:
1. We write code that can be easily maintained and understood by all members of the development and support teams.
2. We believe in solutions and technologies that are pragmatic and not overly-engineered (not using Gulp for the sake of Gulp _FOR EXAMPLE_)
3. We build things in a way that best leverages Apostrophe's tools and and doesn't conflict with patterns already established by Apostrophe (This is the CMS we design and build for ourselves. Don't fight it.)
#### Other ideas:
- We write code that adheres to W3C standards 
- We build websites that comply with WCAG A accessibility standards (_AA and AAA should be something we're prepared to implement when requested by a client_)
- Mobile and responsive should not be an afterthought (we implement these features as we go as opposed to applying them as a band-aid at the end of a project)

...Are these good? What are other ideas? I'd like to have a tentative list drafted by next week. Please send feedback and ideas @agilbert @boutell @stuartromanek @kyjoya @austinstarin @grdunn @bgantick.

**Comment by boutell** [comment]
I like this list. I think some space for growth and improvement in our technology choices is important, but it shouldn't be allowed to eat the schedule and budget of a project.

**Comment by austinstarin** [comment]
I don't mean to throw a book at this answer but the Pragmatic Programmer might be a good reference point to continue this conversation (I believe there's a copy in the P'unk library if you haven't read it):

https://pragprog.com/book/tpp/the-pragmatic-programmer 

Here's a quick reference guide as well:

http://www.ccs.neu.edu/home/lieber/courses/csg110/sp08/Pragmatic%20Quick%20Reference.htm

**Comment by agilbert** [comment]
Great call, Austin. Pragmatic Programmer is great, I could definitely use a refresher on it (been several years) and those who haven't read it would benefit from doing so!

**Comment by colpanik** [comment]
Good recommendation... The quick ref is a great cliffs notes. It would be fun to read/discuss some sections of this book as a group someday. I haven't read it since I worked at Cipher Prime.

There's a bunch of points in the second link that could potentially be mined for ideas, but these all feel too granular... Plus, almost everything on this list **should** be applied to **all** projects, but I'll admit many of them are not sustainable within the budget/timeline constraints we're often faced with.

Remember, we're establishing best practices for people who work on client projects at P'unk Ave. We should try to prioritize values that exist within those realities to make things easier and more productive for our team (and better for our clients, of course).

**Comment by austinstarin** [comment]
Definitely hear you! Was thinking that it would be a good starting point (it's what comes to mind when I think of high level principles that drive my work) — definitely not suggesting a wholesale adoption of all the points that Hunt and Thomas list.

**Comment by austinstarin** [comment]
This is a great look too. It's a list of high level design principles that Jeremy Keith put together from various sources: https://principles.adactio.com/

**Comment by boutell** [comment]
Austin's link nudges me to mention a few things that should be on our list:

* We never make things worse for the sake of making them cool; when we diverge from a well-established convention, we accept full responsibility for addressing everything we're giving up.

For instance, it is not acceptable to break SEO, accessibility or sharing features that would have worked just fine without that AJAX call.

* We always think about how a website will work in a year. We're not generally concerned about "webscale," but we are definitely concerned about questions like: "does the pagination work? What happens when they have 1,000 blog posts in the index? Will the speed be reasonable then? Will it crush mobile phones then? Can they tell what year this article was posted in?"
