### ISSUE TITLE
Gulp

### ISSUE THREAD

**Issue by austinstarin** [punkave/best-practices#15]
I'm proposing that we use Gulp or have the option to use Gulp as a front end build tool.

**Here are some high level reasons:**
- Separation of concerns. There's lots of useful front end tooling out there and a build tool like Gulp let's you customize your tooling per project need. It's great that Apostrophe provides a less build pipeline but it doesn't seem right to build any opinionated tooling into Apostrophe for front end development.
- Competency in a build tool like Gulp or webpack is often a requirement for most modern front end development and it would be awesome to open up opportunities for professional development around this space.

**Here are a few tools that we've been using with Gulp in projects:**
- [Autoprefixer](https://github.com/postcss/autoprefixer) - Autoprefixes your CSS using rules from "Can I Use" so you don't have to think about it.
- [Browserify](http://browserify.org/)  - Let's you use common js and helps with code organization and dependency management.
- [Babel](https://babeljs.io/) -  Compiler that let's you write js with new language features.
- [svgmin](https://www.npmjs.com/package/gulp-svgmin) -  Optimize/manipulate SVG

I also see the opportunity to introduce linting into a build pipeline eventually. When we lock down house standards around css and js we could potentially customize linting configs that we could pipe through our build to actually enforce our standards.

cc/ @agilbert @boutell @colpanik @kyjoya @grdunn @bgantick @stuartromanek

**Comment by boutell** [comment]
I support the judicious use of Gulp. I don't want to see Apostrophe's frontend world grow beyond need, and Gulp provides an excellent alternative to that. 

Gulp also makes sense from a professional development standpoint, both individually and as a company. We do occasionally build things outside of Apostrophe.

I have some concerns about the use of Babel. Specifically, I'm OK with it up until the point where you get past the features included in JavaScript in Node 4.x. I think we create a hazard when we start using js features in the browser that won't exist if we try to use them on the server.

The basic promise of "no context switching, use one language" starts to fall apart.

**Comment by boutell** [comment]
I think our use of Gulp needs to follow best practices such as taking advantage of the new `before-connecting` hook in stagecoach. We should also consider whether we should standardize on some npm bin scripts to "do the things." If the support team knows that "npm build" is always going to work, regardless of whether Gulp or Grunt or Axe Body Seasoning Build Script was used, that's a big win.

**Comment by austinstarin** [comment]
@punkave/developers Hi Friends, I've been thinking about the use of Gulp more for front end builds and am questioning using it.

I'm not sure if gulp makes sense if you're authoring js in `always.js` in most cases. Also wondering if it makes sense to just add less autoprefixer and source maps into Apostrophe core's less pipeline and call it done.

**Comment by boutell** [comment]
I would be good with bringing less autoprefixer and source maps into the core. Although autoprefixer probably should require a flag as I assume it's possible to have a bc issue if it's suddenly thrust into a project.

**Comment by austinstarin** [comment]
I'm going to close this. I opened two issues in Apostrophe for LESS autoprefixer and source maps. Thanks for talking this out team 👍
