### ISSUE TITLE
Mobile Navigation Patterns

### ISSUE THREAD

**Issue by bgantick** [punkave/best-practices#16]
I've seen some support issues pop up around the topic of mobile navigation being broken on a couple projects, so I wanted to address something:

It's fairly common practice to transition the `opacity` of a mobile nav on open/close. If you're doing so, please be sure to do something like toggle the `max-height` and `overflow` as well. Otherwise, the menu remains accessible and clickable - clicks on content "below" the nav will have unexpected/undesirable results because the clicks will be propagating to the invisible menu and not to the content below.

Example:
```
.menu
{
  opacity: 0;
  max-height: 0;
  overflow: hidden;
  .transition(all 0.2s ease);
  &.open
  {
    opacity: 1;
    max-height: 600%; //something ridiculous to ensure content isn't cut off
  }
}
```

What are some other ways that people implement mobile navigation? What's best for accessibility, etc.? I wanted to generate some discussion before I document this.

**Comment by stuartromanek** [comment]
Not sure the best way to structure this but here are some things I think about

- Use the same navigation markup for desktop and mobile where possible
- For elements that need to be clicked or tapped, use HTML elements that have native interaction properties, such as `button`s or `anchor`s
- For full takeover menus that require `overflow:hidden` trickery, test the toggling of overflow thoroughly
- Animate properties that are on the GPU thread for smoother performance (is this the thing that is no longer necessary?)

Unsure what is best for accessibility here, other than using `<nav>` tags and semantic markup ...

**Comment by austinstarin** [comment]
Second everything that @stuartromanek mentions here (not sure about the GPU thread detail).

I would also make it a point to make sure that your drawer doesn't adversely affect sequential tabbing (i.e. you shouldn't get visually "stuck" in the drawer if your tabbing through the site).

You can also write a few extra lines of js to open/close drawers with your keyboard and to capture the focus of the drawer when opened (i.e. you should only be able to tab/focus through the focusable elements of the drawer when opened until it is closed).

**Comment by austinstarin** [comment]
I'm going to close this out. Very broad and has been accounted for in other documentation.
