### ISSUE TITLE
Formalizing Tools for Front-End Client Services

### ISSUE THREAD

**Issue by grdunn** [punkave/best-practices#19]
To continue from our best-practices discussion, I think we should formalize a set of tools we use for front-end builds here @ P'unk Avenue. Ultimately, providing a boilerplate of these tools to help streamline the initial build process, as well as maintain consistency within our codebase.

In my work for PSEA, (which was adopted from @austinstarin 's work for for Penn Parking), I used both a `Gulp` flow, in conjunction with `Harp`.

- [Harp](https://harpjs.com/) provides some tools that lets you build static sites, with some support built in pre-processing for EJS, SASS, Coffeescript, etc. I found the most useful tool was it's data injection. You're able to mockup raw JSON data and inject it throughout your templates. More on that [here](https://harpjs.com/docs/development/metadata).

- Obviously a `Gulp` flow was used here. The biggest reason in this case was so that my files could be watched, reloaded, served without having to refresh my server. Additionaly, `gulp-autoprefixer` has saved me a great deal of time worrying about cross-browser compatibility. https://www.npmjs.com/package/gulp-autoprefixer. More in general, on that here: https://github.com/punkave/best-practices/issues/15

It appears Harp doesn't support Nunjucks, but that could easily be folded into the Gulp build, and served into the `/public` folder that's ultimately served by Harp. I do think there is value in experimenting with other templating languages/technologies from time to time, for general professional growth / experimentation. 

Would love to hear everyones thoughts on a set of tools we all dig, and from there could build out a boilerplate for future projects.

**Comment by grdunn** [comment]
Forgot to link to both PSEA and PTAP

https://github.com/punkave/psea
https://github.com/punkave/ptap

**Comment by agilbert** [comment]
Thanks Greg! I would definitely recommend we continue to iterate on this toolkit for future projects that require this sort of front-end only build.

It seems like `harp` is a good tool, even without nunjucks support. I would generally agree with you about dabbling in other templating languages. And `glup` clearly makes a ton of sense here.
