### ISSUE TITLE
What git branch do we develop new projects in?

### ISSUE THREAD

**Issue by boutell** [punkave/best-practices#25]
Absolutely we should do feature branches for individual features. And sometimes iteration branches make sense too, after launch. That's not what this is about.

This is about answering the question: "I need to work on a project that Bob started. It hasn't launched yet. What branch am I supposed to check out to find the latest completed and peer-reviewed code?"

In my opinion: master!

Why: master is the default branch in a new project. If you just type "git clone project", you get master. What you get by default should be useful if at all possible. It reduces friction.

master was the default in older punkave projects, and is still the default after launch. That also helps make it easy to remember.

Sometimes, in larger projects with higher QA expectations, we might have iteration branches that collect new code for a week or more. But they always wind up merging back to master before deployment.  In general, **if it's live on production it should be safe to assume it is in master**.

In situations where we do use iteration branches, which isn't all that often, we're doing it because the project is already live and QA expectations are higher. For a brand new project, logically QA expectations are lower, and there is even less likelihood that it makes sense not to merge features to master after PR review.

If I "git clone" a project where "develop" is the default branch, I am usually staring at a repo with only a README in it. This feels like a red flag, it indicates there's no meaningful distinction between develop and master; otherwise master would have more in it.

Thoughts?

**Comment by grdunn** [comment]
> In general, if it's live on production it should be safe to assume it is in master.

This, for sure.

I've been using a flow where I create `feature` branches, `support` branches, yada yada, and merge all of that work into a `development` branch, and once i've deployed to production -- merge that over into `master` so it is a complete reflection of what's out in the wild. 

In the event someone is working on a new feature, and merging code into `master` but has not yet deployed -- and simultaneously, a support ticket comes in that requires the support team to pull down `master`, this could become problematic. Having that one extra degree of separation seems important in this case. I treat the `dev` branch as the "most up to date, including potential new features, but not ready for production yet" branch. 

README's could probably use it's own best practices thread.

**Comment by colpanik** [comment]
I agree Tom. Master. If you're doing feature branches, there does't feel like there is a strong case for also having a development branch.

**Comment by austinstarin** [comment]
This sounds good and I'm for less friction.

I know git flow is a very popular branching model (which calls for the use of a develop branch) but it might be too overcomplicated for most projects.

**Comment by colpanik** [comment]
Cool. Lets put a brief sentence or two that covers this in the README.

**Comment by austinstarin** [comment]
Closing this out. It's a duplicate and is accounted for in other documentation.
