### ISSUE TITLE
Look into sizing unit best practices

### ISSUE THREAD

**Issue by colpanik** [punkave/best-practices#27]
When should we be using px and % vs rem?

Is it ok to use px for margin and padding etc?

**Comment by austinstarin** [comment]
I would advise using relative units to size everything.

**Comment by agilbert** [comment]
@austinstarin why?

**Comment by bgantick** [comment]
I have thoughts on this. I did some reading and will compile my notes.

**Comment by austinstarin** [comment]
Generally it _feels_ inline with creating multi context web experiences. That's squishy.

Scroll to bottom of thread here https://github.com/punkave/best-practices/issues/6

**Comment by austinstarin** [comment]
@bgantick any thoughts on this so we can close it out?

**Comment by bgantick** [comment]
Here's what we've been doing (correct me if I'm wrong):

px for borders
unitless line-height
em for media queries
rem for everything else (unless % is appropriate)

**Comment by austinstarin** [comment]
+ 1
