### ISSUE TITLE
Comments as Headers in LESS and JS files?

### ISSUE THREAD

**Issue by jsumnersmith** [punkave/best-practices#3]
In a slack conversation, we turned over potentially taking on a consistent comment style for headers (and potentially titles within a document). In that conversation, we landed on a simple style that seemed to make sense:

```
// ===============================================================
// Title
// ===============================================================

```
Does this feel like something we should codify and turn into a simple article with SublimeText and Atom snippets to get us all easily on the same page?

**Comment by kylestetz** [comment]
That sounds great. Perhaps we can work out a subtitle style as well that would mark separate sections of a file under a single title?

I use breaks like this just for visual separation:
```
// ---------------------------------------------------------------
```
... and sometimes I will throw a subtitle at the end:

```
// --------------------------------------------------------------- SUBTITLE
```

**Comment by boutell** [comment]
In JS files, I would suggest that in most cases you should push more than
one file instead, for much easier navigation. That is, if you feel like you
need a big comment to explain what this half of the file does, why isn't it
a separate file?

I wonder if the same question should be asked about LESS.


On Mon, Jun 8, 2015 at 9:09 AM, Kyle Stetz <notifications@github.com> wrote:

> That sounds great. Perhaps we can work out a subtitle style as well that
> would mark separate sections of a file under a single title?
>
> I use breaks like this just for visual separation:
>
> // ---------------------------------------------------------------
>
> ... and sometimes I will throw a subtitle at the end:
>
> // --------------------------------------------------------------- SUBTITLE
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/frontend/issues/3#issuecomment-109987987>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by jsumnersmith** [comment]
OOOOOooo. What about a snippet that does that, but drops your cursor at the start of the comment line so that our subtitles are:

```
// Subtitle ---------------------------------------------------------------
```

Feels a bit more readable.

**Comment by jsumnersmith** [comment]
@boutell to your point, there are some rare occasions where including more LESS in a file is more pragmatic because you'd be separating your concerns too much. Even in short files, the subheaders can be useful.

**Comment by boutell** [comment]
Yeah, I think it makes sense in a situation where a separate file is too
much structure too soon, but you want to clarify what's what.

On Mon, Jun 8, 2015 at 9:12 AM, Joel Smith <notifications@github.com> wrote:

> @boutell <https://github.com/boutell> to your point, there are some rare
> occasions where including more LESS in a file is more pragmatic because
> you'd be separating your concerns too much. Even in short files, the
> subheaders can be useful.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/frontend/issues/3#issuecomment-109989982>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by kylestetz** [comment]
@jsumnersmith I'd be down with either format!

@boutell when you have a million LESS or JS files, comment sections are really helpful just to know where you are in the world. I think it also builds a good habit of writing code for humans— I don't want to assume that someone understands the intent of a file by the filename.
