### ISSUE TITLE
Better name for this repo?

### ISSUE THREAD

**Issue by jsumnersmith** [punkave/best-practices#4]
Hey all,

While we originally intended this repo to be a "front-end" best-practice repo, I'm starting to feel a vision for it that's bigger than that. Do we have thoughts about what a better name could be?

Some suggestions from Slack:
* `practice`
* `best-practice`, `bestest-practices`
* `pirate-protocol`
* `front-end-style-guide`
* `style-guide`

**Comment by jsumnersmith** [comment]
I'm wanting something to feel as right as 'The Terminal' did for our technical blog.

**Comment by jsumnersmith** [comment]
Hey y'all. Wanted to bump this conversation again. I'm thinking that `best-practices` is the most logical, straightforward name for this. That makes this a good landing spot for information from Darien St.

**Comment by stuartromanek** [comment]
`haus-style`

**Comment by jsumnersmith** [comment]
Maybe `hass-styles` and it's a shortcut to all of @alohaas's best practices.

Talked IRL with Kyle about this, and I think we'll just go with `best-practices` for now because that's blatantly obvious what it is. Skip the metaphors for now.

**Comment by alohaas** [comment]
Maybe I'm late to the party, but `haas-styles` is a very good name for this. 
I support `best-practices` as well.

**Comment by alohaas** [comment]
:+1:
