### ISSUE TITLE
Never use vw for page layout

### ISSUE THREAD

**Issue by boutell** [punkave/best-practices#42]
http://stackoverflow.com/questions/30489594/prevent-100vw-from-creating-horizontal-scroll

The use of 100vw is shiny and happy until somebody tries viewing a page on Windows. A wild scrollbar appears, and according to the (rather useless) specified behavior of vw, 100vw *includes* the width of the scrollbar. So anything set to 100vw, or indeed some fraction of it meant to add up with other elements to 100vw, is now Too Wide.

**Comment by stuartromanek** [comment]
feels like this should be Understand the Implications of VW rather than never use..

**Comment by boutell** [comment]
Is there a scenario where the behavior wouldn't cause problems? Maybe
setting dimensions of a dialog that is nowhere near 100% but it still seems
iffy

**Comment by austinstarin** [comment]
I'm going to close this out.
