### ISSUE TITLE
Should we break JS styleguide in smaller articles?

### ISSUE THREAD

**Issue by jsumnersmith** [punkave/best-practices#5]
First of all, @boutell, bravo! The JS styleguide is a great representation of our JS practices as they currently stand. I think there's room for small tweaks and the like, but it's a solid and comprehensive document. Thanks as always for your hard work. 

The one question I had was about potentially breaking it into smaller articles, with the first section (i.e. the basics of JS) as the landing page. I'd be happy to take a crack at it, and here's what I was thinking of as a jumping off point for the outline:
* JS Style guide (includes basics and links to the other sections)
  * Why and How of Using Lodash
  * Writing Async JS
  * Advanced JS (why/how ES6, OOP, Moog, etc).
  * JS in Apostrophe

Thoughts?

**Comment by boutell** [comment]
I think that's a reasonable breakdown!

**Comment by boutell** [comment]
I would not classify oop as advanced though. Separate it from the optional
