### ISSUE TITLE
Visual state should be managed by toggling classes

### ISSUE THREAD

**Issue by austinstarin** [punkave/best-practices#58]
Don't use `.show()` or '.hide()`.

**Comment by abea** [comment]
I'm a big fan of `is-visible`, `is-active`, etc for state classes, fwiw. One approach is to not set them globally, thus avoiding having to use `!important`. Instead they live inside the component since, for example, `is-active` could mean different things for different modules.

**Comment by austinstarin** [comment]
Agree with the above and is something @bgantick and I have been doing across projects.
