### ISSUE TITLE
Not using "link buttons" for JS event triggers

### ISSUE THREAD

**Issue by abea** [punkave/best-practices#65]
I've seen fairly frequent use of the `a` element as a JS event target when there's no meaningful `href` involved. Per the spec this should be a job for `button` elements. If it's not connected to a form this would be a button with `type="button"` (or maybe no `type`?).

MDN describes anchor tags as, "The HTML <a> element (or anchor element) creates a hyperlink to other web pages, files, locations within the same page, email addresses, or any other URL" (clearer than the spec). Per the spec, "If the `a` element has no href attribute, then the element represents a placeholder for where a link might otherwise have been placed, if it had been relevant, consisting of just the element's contents."

There's a bit of extra styling to override for buttons, but we're running extensive CSS resets most of the time anyway. `button` also is super easy to disable (and style as disabled -- `button:disabled`) and has other built-in benefits for button-like behavior.

**Comment by austinstarin** [comment]
Thanks for writing this up! We're all onboard, although I know there is a lot of use of `a` in legacy projects. 

If this isn't documented somewhere already please do so. Maybe in html or accessibility section?
