### ISSUE TITLE
Folder structure for components and macros

### ISSUE THREAD

**Issue by agilbert** [punkave/best-practices#7]
I'm working on a new project and trying to keep my template organization :ok_hand:. I've been looking at recent projects to help guide me in this pursuit, but I'm seeing some things that feel like they could be tweaked further to be a bit more logical.
### The current (sorta) pattern

Following represents what I've seen in recent projects and had conversations with @jsumnersmith and @colpanik about.

```
/views
  /global
    /components
      index.html   <-- compiles _area.html, _button.html, and _logo.html
      _area.html   <-- macros for areas
      _button.html <-- macros for buttons
      _logo.html   <-- macros for logos
      _header.html <-- the header template
      _footer.html <-- the footer template
```

**Why this is confusing:**

`_area.html`, `_button.html`, and `logo.html` contain _macros_. They are compiled into `index.html` and included in `layout.html` so that all templates can reference them as needed.

 `_header.html`, and `_footer.html` are what we used to refer to as _partials_. Small, re-useable chunks of markup. When they are included in a template, they are simply rendered right away.

Having these share the same folder and naming structure feels confusing and inconsistent to me. I wanted get others' opinion on this and share a few options to consider.
### Some new options to consider

**Option 1: Separate folder for macros**

```
/views
  /global
    /components
      header.html
      footer.html
    /macros
      index.html
      _area.html
      _button.html
      _logo.html
```

**Option 2: Macros nested within components**

```
/views
  /global
    /components
      /macros
        index.html
        _area.html
        _button.html
        _logo.html
      header.html
      footer.html
```

**Option 3: Use macros.html as the compiler**

```
/views
  /global
    /components
      macros.html
      _area.html
      _button.html
      _logo.html
      header.html
      footer.html
```

I'm especially interested in understanding better how the conventions in the naming of the templates can best align with conventions in the naming of widgets, less files, and other elements that they are related to.

(For what it's worth, I think I'm going to be moving forward for now with option 3.)
### Regarding use of _ for compiled files

Based on my understanding, the use of `_` in a file name is to reference items that are supposed to be compiled into another file. You'll notice that in all of my proposed examples, I've removed the `_` from the template files that are not compiled, but rather included into another template as a chunk of markup (`footer.html`, `header.html`).

Is it safe to say that we can and should eliminate underscore prefixes from template files that are not compiled into a parent file? Or does that require further discussion?

**Thanks in advance for any and all thoughts and feedback on this subject!**

**Comment by jsumnersmith** [comment]
Just another minor thought here, but we also talked about macro files using the word macro in their title: 
`_buttons-macro.html` or `_buttons.macro.html1`. So it might look something like:
```
/views
  /global
    /components
      index.html   <-- compiles _area.html, _button.html, and _logo.html
      _area-macro.html   <-- macros for areas
      _button-macro.html <-- macros for buttons
      _logo-macro.html   <-- macros for logos
      _header.html <-- the header template
      _footer.html <-- the footer template
```

Another idea, for visual separation could putting the `macro` first.
```
/views
  /global
    /components
      index.html   <-- compiles _area.html, _button.html, and _logo.html
      _macro.area.html   <-- macros for areas
      _macro.button.html <-- macros for buttons
      _macro.logo.html   <-- macros for logos
      _header.html <-- the header template
      _footer.html <-- the footer template
```

**Comment by agilbert** [comment]
To me, an `index.html` file implies that it's there to compile all of the other files in the directory. Does anybody else feel that way?

Also, @jsumnersmith what did you think of the possibility of dropping the `_` prefix on templates that aren't there to be compiled?

**Comment by jsumnersmith** [comment]
@agilbert I could go either way. If we use some sort of "macro-in-the-name" approach, I could easily get behind dropping it.

**Comment by boutell** [comment]
I'm not passionate about this, beyond choosing something with better
namespacing than what we have now. But if it were up to me, I'd go with
option one, plus get rid of the underscores (no longer making a necessary
distinction), and I wouldn't use "index.html" because that sounds like you
can look at it. I'd use "all.html" because that's its job — import
everything.

My beef with "compile" is that you could import just one of the macro files
if you wanted. You do not need to "compile" them, they are perfectly fine
to import individually.

Although... maybe we're using "compile" in its original pre-geek sense and
I'm the only one who thinks the verb is weird.

Also we should think about 0.6 organization. In 0.6 you cannot define
macros with "include", you must use "import". I am pretty sure that means
you can't have an "all.html", unless Jimmy and Matt and Kerry have found a
workaround?

On Fri, Mar 18, 2016 at 2:45 PM, Joel Smith <notifications@github.com>
wrote:

> @agilbert <https://github.com/agilbert> I could go either way. If we use
> some sort of "macro-in-the-name" approach, I could easily get behind
> dropping it.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/best-practices/issues/7#issuecomment-198490927>
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by jth-** [comment]
Yeah, I'm pretty sure you can't have `all.html` in 0.6, since including imports won't define them in the scope that you are including them into. I also don't think you can do you imports in a layout-level file, because the imports won't be defined in the scope of the templates that extend the layout.

My current pattern in 0.6 is to configure a views fallback folder at top-level (i.e. `project/views) with a macros folder within that. I then import those macros as needed, without needing to cross-module import because I'm essentially adding all the macro files to the base `apostrophe-module`. For example:

`app.js`
```
...
'apostrophe-templates': { viewsFolderFallback: __dirname + '/views' },
...
```

`/views/macros/button.html`
```
{% macro default(label, url) %}
  <a href="{{ url }}">{{ label }}</a>
{% endmacro %}
```

`/lib/modules/things-pages/views/index.html`
```
{% extend "apostrophe-templates:layout.html %}
{% import "macros/button.html" as button %}
{% block main %}
  {% for piece in data.pieces %}
    {{ button.large(piece.title,piece._url) }}
  {% endfor %}
{% endblock %}
```

Note, no cross module import for the buttons, and what I'm doing is very explicit. No hidden mystery macros.

**Comment by boutell** [comment]
Yeah, I like how this makes everything explicit, even if it could be
tedious in a file that uses a lot of macro types.

On Thu, Mar 24, 2016 at 10:07 AM, Jimmy Harrison <notifications@github.com>
wrote:

> Yeah, I'm pretty sure you can't have all.html in 0.6, since including
> imports won't define them in the scope that you are including them into. I
> also don't think you can do you imports in a layout-level file, because the
> imports won't be defined in the scope of the templates that extend the
> layout.
>
> My current pattern in 0.6 is to configure a views fallback folder at
> top-level (i.e. project/views) with a macros folder within that. I then
> import those macros as needed, without needing to cross-module import
> because I'm essentially adding all the macro files to the baseapostrophe-module`.
> For example:
>
> app.js
>
> ...
> 'apostrophe-templates': { viewsFolderFallback: __dirname + '/views' },
> ...
>
> /views/macros/button.html
>
> {% macro default(label, url) %}
>   <a href="{{ url }}">{{ label }}</a>
> {% endmacro %}
>
> /lib/modules/things-pages/views/index.html
>
> {% extend "apostrophe-templates:layout.html %}
> {% import "macros/button.html" as button %}
> {% block main %}
>   {% for piece in data.pieces %}
>     {{ button.large(piece.title,piece._url) }}
>   {% endfor %}
> {% endblock %}
>
> Note, no cross module import for the buttons, and what I'm doing is very
> explicit. No hidden mystery macros.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/best-practices/issues/7#issuecomment-200852944>
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by agilbert** [comment]
Thanks for the additional thoughts, Jimmy.

> Yeah, I'm pretty sure you can't have all.html in 0.6, since including imports won't define them in the scope that you are including them into. I also don't think you can do you imports in a layout-level file, because the imports won't be defined in the scope of the templates that extend the layout.

I think I'm following this, but want to confirm that this relates to `0.6` only and so the recommendations and patterns you're talking about here wouldn't apply to the work I'm doing just yet.

**Comment by jth-** [comment]
Agreed, while those patterns would work similarly in an `0.5` project, it's probably not worth it to shift the paradigm for those projects right now.

**Comment by agilbert** [comment]
I just made a relatively major shift in my conventions with the above commit. Overall, it feels simpler and more logical to me, but would love some input from other folks that are part of this conversation.

**Comment by agilbert** [comment]
The structure I'm now using is:

```/views
  /global
    /components
      header.html
      footer.html
      macros.html <-- loads in all files in macros/ as a convenience
    /macros
      area.html
      button.html
      logo.html
```

Also worth mentioning is that I've removed all of the `_` from my less files as well. I had already moved away from using an `index.less` in each `public/css/` subdirectory, so the value of having the `_` in the filename was diminished. Now *nothing* has an `_` in the filename, the 1-to-1 relationship between names of templates and less file is still there, and things are simpler overall.

**Comment by boutell** [comment]
Alex, in this scheme, where do the various LESS files get imported?

On Thu, Mar 24, 2016 at 3:44 PM, Alex Gilbert <notifications@github.com>
wrote:

> The structure I'm now using is:
>
>   /global
>     /components
>       header.html
>       footer.html
>       macros.html <-- loads in all files in macros/ as a convenience
>     /macros
>       area.html
>       button.html
>       logo.html
>
> Also worth mentioning is that I've removed all of the _ from my less
> files as well. I had already moved away from using an index.less in each
> public/css/ subdirectory, so the value of having the _ in the filename
> was diminished. Now *nothing* has an _ in the filename, the 1-to-1
> relationship between names of templates and less file is still there, and
> things are simpler overall.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/best-practices/issues/7#issuecomment-200987598>
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by agilbert** [comment]
In [public/css/site.less](https://github.com/punkave/greenetowne/blob/news-and-stories/public/css/site.less).

**Comment by boutell** [comment]
I see.

On Thu, Mar 24, 2016 at 4:14 PM, Alex Gilbert <notifications@github.com>
wrote:

> In public/css/site.less
> <https://github.com/punkave/greenetowne/blob/news-and-stories/public/css/site.less>
> .
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/best-practices/issues/7#issuecomment-201001451>
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by colpanik** [comment]
Where are we at with this? Are people using still `index.less` files in different directories with partials or mistakenly still using `_index.less`? Same question for macros.

For macros/html components, I like to follow a pattern similar to what @agilbert had described above:

```
  /global
    /components
      header.html
      footer.html
      macros.html <-- loads in all files in macros/ as a convenience
    /macros
      area.html
      button.html
      logo.html
```

For stylesheets, I tend to favor using `site.less` as the place where all my less partials are imported:

```less
// utils
@import "utils/_reset";
@import "utils/_mixins";
@import "utils/_breakpoints";

// global
@import "global/_unit";
@import "global/_color";
@import "global/_type";
@import "global/_grid";
@import "global/_admin";

// components
@import "components/_box";
@import "components/_button";
@import "components/_circleCallout";
@import "components/_marquee";
@import "components/_navigation";
@import "components/_footer";

// blocks
@import "blocks/_mixedPic";
@import "blocks/_circlesPic";
```

I think we should formalize this.

**Comment by agilbert** [comment]
I am personally against the `_` prefix, but otherwise 👍

**Comment by austinstarin** [comment]
Closing this out. Too broad off a topic and has been open for over a year.
