### ISSUE TITLE
Change numbered section item to h3

### ISSUE THREAD

**Issue by austinstarin** [punkave/best-practices#70]

**Comment by abea** [comment]
How concerned are we with preserving legacy external links? I'd think not so much since this is an internal document and fairly in flux already. Current anchors like `#semanticHtml--buttons` couldn't be recreated with a heading.

**Comment by austinstarin** [comment]
It's nice to be able to link directly to the entry

**Comment by abea** [comment]
Github creates anchors for all headings . At least down to H3 if not lower. It'd only be an issue if we moved this out of Github.

**Comment by austinstarin** [comment]
Sounds good.
