### ISSUE TITLE
Version control hotfix practice

### ISSUE THREAD

**Issue by abea** [punkave/best-practices#79]
The current version control doc doesn't mention `hotfix` for changes on master. 

From [Introducing Git Flow](https://datasift.github.io/gitflow/IntroducingGitFlow.html):
"They are branched directly from a tagged release in the master branch, and when finished are merged back into both master and develop to make sure that the hotfix isn’t accidentally lost when the next regular release occurs."

I might also include a mention that in post-launch support, feature updates or additions should go through the `develop` branch and versioning, but bug fixes can go through `hotfix`.

**Comment by austinstarin** [comment]
Thanks, let's include this.
