### ISSUE TITLE
Styling Apostrophe classes

### ISSUE THREAD

**Issue by abea** [punkave/best-practices#86]
I think we should set a practice that any styling of apostrophe classes (e.g., `.apos-tweet`, `[class ^= 'apos-']`) should be scoped to the component level. And as tightly as possible. Scoping to the project level causes problematic specificity fights to override.

**Comment by austinstarin** [comment]
Can you clarify this with an example?

I would advocate not to scope anything project level to an `apos` prefixed selector.

If you need to push Apostrophe UI around, it might be best to use a project level wrapper.

For example...

```
<div class="my-wrapper">
  {{ apos.singleton(data.page, 'foo', 'foo') }}
</div>
```

**Comment by austinstarin** [comment]
@abea are you okay w/ this solution? May I close?

**Comment by abea** [comment]
Yeah, that's fine.
