### ISSUE TITLE
Provide reasons for linter disabling

### ISSUE THREAD

**Issue by abea** [punkave/best-practices#87]
When using the linter disabling comments (e.g., `// eslint-disable-line`), we should limit it to the specific rule at issue (e.g., `// eslint-disable-line space-before-function-paren`). Examples are eslint, but same is the case for stylelint.

If disabling a linter for a larger block of code, a reason should be provided in a comment on a second line for future code maintainers. This will help alert future devs if there's a potential pitfall there or if it might be something that can be fully fixed later.

**Comment by austinstarin** [comment]
Sounds reasonable, thank you for being thoughtful about this.

**Comment by austinstarin** [comment]
This needs documentation.
