### ISSUE TITLE
Sass extend with placeholders

### ISSUE THREAD

**Issue by abea** [punkave/best-practices#88]
To use `@extend` with placeholder selectors as a rule to avoid unintended output.

Self-promoting argument reference: http://alexbea.com/2016/01/10/sass-extends.html

**Comment by austinstarin** [comment]
This seems fine to me. Can we open it up to the rest of the team... cc/ @bgantick @mtthwmnc @arti5m

**Comment by bgantick** [comment]
Seems fine
