### ISSUE TITLE
Managing z-index

### ISSUE THREAD

**Issue by austinstarin** [punkave/best-practices#9]
## Setting z-index values

Consider using values of `10` for `z-index`.  This pattern provides a range of values to use if you need to add elements between other elements in the stacking context.

This also creates constraints and forces you to be intentional about how you set these values. 
## Managing z-index values

Sass maps are great to keep `z-index` values in a central key/value store for a UI.

I'm still looking for a good equivalent helper in less...

``` sass
$z-index: (
  modal: 900,
  drawer:  200,
  tray:  400
 );
```

``` sass
.modal {
   z-index: map-get($z-index, modal);
}
```

**Comment by abea** [comment]
Regardless of ability to use maps for these, I fully second having them all in a single variables or settings partial. Easy to spot and squash use of `z-index: 9999999;`. I might go further and [use a stylelint plugin](https://github.com/AndyOGo/stylelint-declaration-strict-value) to help enforce this.

**Comment by austinstarin** [comment]
@abea  See https://github.com/punkave/stylelint-config-punkave/issues/25

Was talking to @bgantick. I think we should enforce variable use for `z-index`. The variables should be named semantically like `@z-index-modal`. We should ideally use values like `1, 2, 3, 4` etc.  In other words, values shouldn't be arbitrary and their assignment should show competency in how you are layering the stacking order.

**Comment by abea** [comment]
Cosigned. And specifically in a single partial. I'm not sure if it's changed by most projects I'm seeing have variables spread across multiple files and not always in obviously consistent ways.

**Comment by austinstarin** [comment]
Good additional point.

So it would make sense to have a `_z-index.less` in your `settings` dir.

**Comment by abea** [comment]
Or if we have a _layout.less file it could include gutter and grid stuff as well in case there isn't enough use for a whole partial on its own.

**Comment by austinstarin** [comment]
Good thought. Let's leave this point vague for now and we can revisit this specifically when we work on our front-end starting point for all projects. I will take the lead on documenting this.
