### ISSUE TITLE
aria landmark roles are handled implicitly by HTML5 element use

### ISSUE THREAD

**Issue by austinstarin** [punkave/best-practices#92]
We should remove https://github.com/punkave/best-practices/blob/master/accessibility.md#aria

**Comment by abea** [comment]
A note about HTML5 elements communicating roles seems worth having. Then a note about using ARIA for more complex interactive components could cover the rest, possibly linking to [Heydon Pickering's examples](http://heydonworks.com/practical_aria_examples/)
